name: Build and Deploy on Release
# Controls when the workflow will run
on:
  release:
    types: [ published ]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    name: Setup, Build and Publish    
    runs-on: ubuntu-latest
    
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Get Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: 'Login to docker with GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build with Maven"
        working-directory: ./Stevedores
        run: |
          mvn clean compile com.google.cloud.tools:jib-maven-plugin:3.0.0:build \-Dimage=ghcr.io/${{ github.repository_owner }}/stevedores-b:${{ env.RELEASE_VERSION }}
      - name: Send Deploy Notification to Integration Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: com619-2021/IntegrationB
          event-type: deploy
          client-payload: '{"image_owner": "STEVEDORE_IMAGE", "image_tag": "ghcr.io/${{ github.repository_owner }}/stevedores-b:${{ env.RELEASE_VERSION }}"}'
